CREATE TABLE endereco(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cep VARCHAR(8),
  logradouro VARCHAR(100) NOT NULL,
  complemento VARCHAR(20),
  bairro VARCHAR(40) NOT NULL,
  municipio VARCHAR(50) NOT NULL,
  estado VARCHAR(2) NOT NULL
);